### ISSUE TITLE
Property helper could handle class binding with attribute()

### ISSUE THREAD

**Issue by vallo87** [Chialab/dna#29] opened 2017-05-10 15:04 UTC
when binding a property of a component with Property helper i would like to be able to sync that property with the class list 
- Bolean prop, true -> classList has prop added
- Bolean prop, false -> classList has prop removed
- Other prop value -> classList has value added

**Comment by edoardocavazza** [comment] 2017-11-23 09:25
Duplicate of #17

**Closed by edoardocavazza** 2017-11-23 09:25 UTC
